openSUSE/doc-kit

- asciidoc-release-notes/adoc/attributes-generic.adoc
- asciidoc-release-notes/adoc/attributes-product.adoc
Move them to attributes-product.adoc because
they are product-specific, which also fixes
errors caused by them being used before they
are defined.
I have already made this change manually in most repositories so this only syncs the template with the reality.
Fixes #19
> Move attributes using {product}

- asciidoc-release-notes/README.adoc
I've now changed it in most repositories to the trimmed README we've agreed upon but it would be good to have it here so we can make changes in one central location in the future.
If I'm not mistaken, so far the only repository that has custom README is SLES.
> Change initial README to something useful

- asciidoc-release-notes/adoc/attributes-product.adoc
- asciidoc-release-notes/adoc/release-notes-docinfo.xml
I tested it and it works in OBS so I think it's a good addition to the AsciiDoc RN template.
I've used your original commit message as the commit message.
---
This adds the word "(prerelease)" to <productnumber/> whenever the
document is built with `make pdf LIFECYCLE=beta`.
Surprisingly enough, substitution of attributes in Docinfo files now(?)
works without any fuss,
https://docs.asciidoctor.org/asciidoctor/latest/docinfo/ .
I have not tested this within the context of OBS, I hope it works with
AsciiDoctor version available there, too.
Co-authored-by: sknorr <sknorr@suse.de>
> attributes: Trigger <productnumber/> change with LIFECYCLE=beta

- .editorconfig
- KITS
- docbook5-book/xml/generic-entities.ent
- docbook5-book/xml/product-entities-cc.ent
- docbook5-book/xml/product-entities-gfdl.ent
- docbook5-entities-only.MANIFEST
This hopefully makes it easier for existing projects to use at least some of the Doc Kit updatery.
You'd only have to replace the entity files. The intro files are not included here but you can always switch to the full DocBook 5 book kit.
> db5 ent: Add DocBook 5 entities only kit

- docbook5-book/xml/MAIN.book-example-cc.xml
- docbook5-book/xml/MAIN.book-example-gfdl.xml
To make the 'Edit Source' links available in our HTML builds, we need `<dm:editurl>` in the MAIn files, e.g.
` <dm:editurl>https://github.com/SUSE/doc-sle/edit/main/xml/</dm:editurl>`
Adding a placeholder.
> db-5 book: add <dm:editurl> to MAIN

- docbook5-book/xml/generic-entities.ent
The expansion for the &ulp; entity was updated from 'userspace live patching' to 'user space live patching'.
> Update the spelling of 'user space live patching'

- docbook5-book/xml/generic-entities.ent
In the SLE HA repo this guide used the same entity name (instquick) as the SLE installation quickstart. Unfortunately the two guides do not have the same title (that would have been very convenient).
> Add entity for HA installation quickstart

- docbook5-book/xml/common_license_gfdl1.2.xml
As discussed in the meeting this morning, I have checked all XML files within `docbook5-book` to make sure the translation flags are set correctly. The only file which was missing a `<dm: translation>` element was `common_license_gfdl1.2.xml` (which is an XInclude), but I have added an `info ` element with this tag there as well and set it to `no`, as we usually do not translate the GFDL text.
With this PR, all template files should now have the correct translation flags set.
In this wake, I have discovered that two more files are outdated (contentwise) meanwhile, but I will create a separate PR for those.
> Set translation flags correctly

- docbook5-book/xml/MAIN.book-example-cc.xml
- docbook5-book/xml/MAIN.book-example-gfdl.xml
- docbook5-book/xml/product-entities-cc.ent
- docbook5-book/xml/product-entities-gfdl.ent
Fixes DOCTEAM-828 which was discussed in SLE Writers Call on 2022-11-21. It contains additions of the entity `&productnameshort;` and a XML structure that uses it.
I'm wondering if we should amend `adoc/attributes-product.adoc` too. :thinking: Something like this:
```adoc
:product: ProductName
:productnameshort: Acronym
:producta: PN
```
> Introduce &productnameshort; entity

- docbook5-book.MANIFEST
Adjust docbook5-book.MANIFEST: `common_intro_available_doc.xml` should always be updated, not just initially (as agreed in our internal channel on 2023-09-12).
Related issues: https://github.com/openSUSE/doc-kit/issues/63
> MANIFEST: always update common_intro_available_doc.xml

- docbook5-book/xml/generic-entities.ent
Related to the discussion in https://github.com/openSUSE/doc-kit/pull/71: Within our texts, we still use some general entities provided by DocBook4, like:
- nbsp
- dash 
- ndash
- trade
- copy
- sol
- rdquo
- ldquo
Moving them to `generic-entities.ent` removes our need to keep the DB4 package for legacy reasons (as we have moved on to DB5 meanwhile).
> generic: add DB4 entities

- docbook5-book/xml/generic-entities.ent
:information_source: Something to be discussed next week.
As our docs are written in DocBook 5 now, we would like to reduce the dependency for pre-defined DocBook 4 entities. This line contains this reference in the `generic-entities.ent` file:
"-//OASIS//ENTITIES DocBook Character Entities V4.5//EN"
"http://www.oasis-open.org/docbook/xml/4.5/dbcentx.mod"
We already have defined the most used entities from doc-sle and integrated them in PR #72. The reference is not needed anymore.
---
When we migrated from DocBook 4 to DocBook 5, we needed these entities. However, I think, this is no longer the case:
* Although sometimes convenient, the DocBook 4 entities are kind of a "relict" from the DTD era. The DTD defined and used them and so they were automatically available in every DocBook 4 …
> Remove DocBook 4 dependency (entities)

- entities/generic-entities.ent
Some of the entities covered in the `product-entities.ent` file in the `doc-modular` repo need to be moved to `generic-entities.ent`:
```
<!ENTITY kvmserver               "&kvm; Server">
<!ENTITY kvmclient               "&kvm; Client">
<!ENTITY neuvector               "NeuVector">
[...]
<!ENTITY alp-installer           "Agama">
<!ENTITY keylime                 "Keylime">
<!ENTITY snapper                 "Snapper">
<!ENTITY opensm                  "opensm">
<!ENTITY infiniband              "InfiniBand">
<!ENTITY subnetmanager           "Subnet Manager">
```
> generic-ent: add entities from doc-modular

- docbook5-book/xml/common_intro_available_doc.xml
- docbook5-book/xml/common_intro_convention.xml
- docbook5-book/xml/common_intro_feedback.xml
Fixes several issues with the common_intro* files in the preface of our books.
- jsc#DOCTEAM-141: Knowledgebase base (TIDs)
- jsc#DOCTEAM-879: enhance typography section in prefaces (doc-kit)
- remove an entity in `common_intro_feedback.xml` that prevented the example PDF from building (just based on the boilerplate files being delivered by doc-kit). 
The latter will also help to fix https://github.com/SUSE/doc-styleguide/issues/135 as per suggestion in https://github.com/SUSE/doc-styleguide/issues/135#issuecomment-1833649882.
> docbook5-book: enhance preface 

- docbook5-book/xml/common_copyright_cc.xml
- docbook5-book/xml/common_copyright_gfdl.xml
- docbook5-book/xml/common_intro_feedback.xml
- docbook5-book/xml/common_license_gfdl1.2.xml
- smart-doc/common/legal.xml
- smart-doc/common/license_gfdl1.2.xml
Our tools reported some broken links. Updating the links to use https where available. 
Applying the changes from doc-sle/PR#1635 to the boilerplate files managed by doc-kit.
* related PR for doc-sle: https://github.com/SUSE/doc-sle/pull/1635
> fix links: http -> https

- entities/generic-entities.ent
The generic-entities.ent file misses some more DB4 entities: 
- rsquo
- times
- verbar
The entities are used in the following repositories:
- doc-sleha (see failing GHA for https://github.com/SUSE/doc-sleha/commit/4eef48c23f2ae3229fef64550ed19992a0aecbc3)
- doc-hpc (see failing GHA for https://github.com/SUSE/doc-hpc/commit/85bc81280eefe08d39c33907855e1d18345c6ca9)
> Entities: add missing DB4 entities

- docbook5-book/xml/common_license_gfdl1.2.xml
- smart-doc/common/license_gfdl1.2.xml
If the content of a `<link>` tag and its `xlink:href` attribute content is the same, it's better to remove the content. It doesn't bring any benefit and is harder to read and more error-prone.
=> Make `<link/>` an empty link.
* n/a
> Remove content from <link> and make it empty

- entities/generic-entities.ent
According to our Style Guide, the use of entities for URLs is discouraged. But we still offer them in several entity declaration files.  
For now, I removed the ones for composite URLs in generic-entities.ent and added a comment for the remaining ones.  
My question is:
- Should we remove all URL entities? 
- Or should we keep the general ones in ll.214-218? (for stand-alone use this would be OK IMHO)
Style Guide, see https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-link-to-susecom:
"Make sure to use complete URLs instead of entities for an easy copy and paste"
If there are any side-effects that come with the entity …
> Entities: Remove composite URLs with entities

- docbook5-book/DC-example
- smart-doc/_DC-article
We recently stumbled across a validation mismatch between local validation and validation with the daps2docker container. Adding one line to the DC files fixes that.
> DC files: add validation with latest GeekoDoc version

- entities/generic-attributes.adoc
As the doc-kit for adoc books is [a recent addition](https://github.com/openSUSE/doc-kit/pull/106), this doc-kit is not used in any maintenance branches yet. Therefore the product name change from 'SUSE Manager' to 'SUSE Multi-Linux Manager' was straightforward: replacing the SuMa attributes with new ones, based on the [related change for the DocBook variant](https://github.com/openSUSE/doc-kit/pull/107). No need to keep the old attributes around.
https://jira.suse.com/browse/DOCTEAM-1754
> SuMa -> SMLM (adoc kit)

- docbook5-book/xml/MAIN.book-example-cc.xml
- docbook5-book/xml/MAIN.book-example-gfdl.xml
- smart-doc/articles/assembly.asm.xml
The recent localization drops revealed some issues with regards to character limitations for metadata and title length.
Updated the templates for two kits according to the latest agreements: 
-  [smart-doc](https://github.com/openSUSE/doc-kit/tree/main/smart-doc)
-  [docbook5-book](https://github.com/openSUSE/doc-kit/tree/main/docbook5-book)
For the latter, metadata elements had been missing altogether -> added those. 
https://github.com/SUSE/doc-styleguide/pull/330
https://github.com/openSUSE/suse-xsl/issues/737
> Update templates for correct metadata/title length
