openSUSE/doc-kit

docbook5-book/xml/generic-entities.ent

This PR contains just one line for adding the `pace` entity. :wink: I think, this is missing for HA.

Add missing pace entity for HA

---

docbook4-release-notes/gitignore
docbook5-book/gitignore
docbook5-book/xml/generic-entities.ent

Enhanced gitignore + suggested new general entities

---

asciidoc-release-notes/adoc/attributes-generic.adoc
asciidoc-release-notes/adoc/attributes-product.adoc

All of these are already used somewhere so this only brings the template up-to-date.

Add attributes from other products

---

.editorconfig
asciidoc-release-notes.MANIFEST
asciidoc-release-notes/editorconfig
docbook4-release-notes.MANIFEST
docbook4-release-notes/editorconfig
docbook5-book.MANIFEST
docbook5-book/editorconfig

The main file is placed in the repo root so we can benefit from it inside the repo as well.
The other files in sub-folders are symbolic links.
Closes #26

Add .editorconfig

---

asciidoc-release-notes/adoc/about-documentation.adoc
asciidoc-release-notes/adoc/about-product.adoc
asciidoc-release-notes/adoc/attributes-product.adoc

Inspired by https://bugzilla.suse.com/show_bug.cgi?id=1188302.

AsciiDoc RN: various changes

---

asciidoc-release-notes/Makefile

Co-authored-by: Frank Sundermeyer <fs@suse.com>
From https://gitlab.suse.de/documentation/release-notes-sles/-/merge_requests/297

Makefile cleanup

---

docbook5-book/xml/generic-entities.ent

Add entity for old book name: JeOS Quick Start

generic-ent: add JeOS Quick Start (old)

---

docbook5-book/xml/common_intro_feedback.xml

text aligned with common_intro_i.xml from doc-sle 
see also https://github.com/SUSE/doc-sle/pull/1093

align text with doc-sle

---

docbook5-book/xml/generic-entities.ent

SLES BCI should be SLE BCI. This PR fixes it.

SLE BCI abbr

---

asciidoc-release-notes/adoc/attributes-generic.adoc

Added container and BCI-related attibutes.

Add container attributes

---

docbook5-book/xml/common_intro_available_doc.xml

- based on 28eb68346fe1f6b8351bee12a8e73e148720bd1a
* remove detailed list of topics (is available from TOC), see also 
https://github.com/SUSE/doc-sle/pull/781 
* add snippet about RN
* add snippet for docs in (file) system

Intro Available Docs: add recent version from doc-sle*

---

docbook5-book/xml/common_intro_convention.xml

Adding profiling for SLE Micro and replace arch entities. @tomschr @lvicoun : Please check if this makes sense to add.

common conventions: suggest changes from SLE repo

---

docbook5-book/xml/common_intro_support.xml

- see also https://github.com/SUSE/doc-sle/pull/1534

common_support: apply proofing corrections by Dublin

---

docbook5-book/xml/common_intro_available_doc.xml

- based on feedback covered in bsc#1213642 and by fs

available doc: specify 'In your system'

---

asciidoc-release-notes/adoc/attributes-generic.adoc
docbook5-book/xml/generic-entities.ent

Fix KIWI entity to "KIWI NG"

---

docbook5-book/xml/generic-entities.ent

citetitle removed in generic_entities for book titles because of l10n issues (citettitle is blocked for translation)

rm citetitle

---

docbook5-book/xml/generic-entities.ent

SLE product names changed as approved by PMs.
Please apply changes to all SLE repos and branches
For more detail info see: https://jira.suse.com/browse/DOCTEAM-1133

change SLE product names as approved

---

docbook5-book/xml/generic-entities.ent

...as it was missing after other DB4 entity addition

Added mdash entity

---

entities/generic-entities.ent

Define bci-product

---

entities/generic-entities.ent

Sort the list of DocBook 4 entities. Consolidate the "CHARACTER ENTITIES" section and integrate it into the list of DB4 entities.

Sort DocBook 4 entities

---

entities/generic-entities.ent

`minvm` now expands to `SLES Minimal VM`

Update minvm entity

---

entities/generic-entities.ent

update/add ALP-related entities (WIP)

---

entities/generic-entities.ent

Small change that shouldn't impact anything important; I don't think we use this entity anywhere yet? 

Update entity from HPC Guide to &hpc; Guide

---

docbook5-book/xml/common_intro_support.xml

Added profiled link to virt support

---

smart-doc/_DC-article
smart-doc/articles/assembly.asm.xml

Adjust the Smart Docs templates to match our current requirements. 
- update Bugzilla links in assemblies: see https://github.com/SUSE/doc-modular/pull/361 as reference
- [...]

Smart Docs: update templates

---

smart-doc/articles/assembly.asm.xml

Minor updates to the assembly template: titles of assembly and meta title, meta description and social description. 
Based on Jira tickets from portal feedback:
* https://jira.suse.com/browse/DOCTEAM-1612
* https://jira.suse.com/browse/DOCTEAM-1613

assembly template: latest updates

---

entities/generic-entities.ent

Adding new entities for third-party products. 
Based on the following PR: https://github.com/SUSE/doc-modular/pull/339

generic-entities: new entities (3rd party products)

---

entities/generic-entities.ent

Move 'old' entities for SUSE Manager products to section 'Legacy Compatibility Entities' and adding new entities for 'SUSE Multi-Linux Manager' products.
https://jira.suse.com/browse/DOCTEAM-1754

SuMa -> SMLM

---

asciidoc-release-notes/adoc/attributes-generic.adoc
entities/generic-attributes.adoc
entities/generic-entities.ent

Describe the overall goals of this pull request.
* bsc#...
* jsc#...

Change Application to applications for SAP

---

entities/generic-entities.ent

SUSE Liberty Linux is now SUSE Multi-Linux Support.

Liberty: update productname

---

entities/generic-attributes.adoc
entities/generic-entities.ent

In preparation for working in doc-modular, I've moved some generic HA entities to doc-kit's generic entities files. I didn't remove/change any of the ones that were already there, in case they're used elsewhere, even though some of them are pretty old.
* bsc#...
* jsc#...

Add more generic HA entities

---

entities/generic-attributes.adoc
entities/generic-entities.ent

Officially the name is HA Web Konsole (see output of `zypper search hawk`). I don't think this term is used either way anywhere outside of HA 12 SP5, but we might as well update it. 
* bsc#...
* jsc#...

HA Web Console -> Konsole

---

entities/generic-attributes.adoc
entities/generic-entities.ent

Updating the crmsh entities based on https://crmsh.github.io/
It might cause some shenanigans in the SLEHA 15 repo, but I'll take care of that.  
* bsc#...
* jsc#...

Update crmsh entities
